# Generated by Django 5.1.4 on 2024-12-28 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_customuser_address_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='preferences',
        ),
    ]
