# Generated by Django 5.1.4 on 2024-12-28 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_customuser_preferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
    ]
