# Generated by Django 5.1.4 on 2024-12-28 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_customuser_github_link_customuser_instagram_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='github_link',
            new_name='github',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='instagram_link',
            new_name='instagram',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='linkedin_link',
            new_name='linkedin',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='twitter_link',
            new_name='twitter',
        ),
    ]
