# Generated by Django 5.1.4 on 2024-12-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_customuser_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="profile_pictures/default_profile_picture.png",
                null=True,
                upload_to="profile_pictures/",
            ),
        ),
    ]
